language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
    - "rclient/node_modules"
before_script:
  # For now, let's share flow settings.
  - cd rclient; npm install
script:
  - npm test
  - npm run flow-check
  - npm run lint
